[build]
builder = "nixpacks"

[deploy]
startCommand = "python start_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PORT = { default = "8000" }
PYTHONPATH = { default = "/app" }